kvmd:
    server:
        host: 127.0.0.1
        port: 8081
        heartbeat: 3.0

    log:
        services:
            - kvmd.service
            - kvmd-tc358743.service

    hid:
        pinout:
            reset: 4

        device: /dev/ttyAMA0
        speed: 115200
        reset_delay: 0.1

    atx:
        pinout:
            power_led: 24
            hdd_led: 22
            power_switch: 23
            reset_switch: 27

        click_delay: 0.1
        long_click_delay: 5.5

        state_poll: 0.1

    msd:
        pinout:
            target: 12
            reset: 13

        device: "/dev/kvmd-msd"
        init_delay: 2.0
        reset_delay: 1.0
        write_meta: true
        chunk_size: 65536

    streamer:
        pinout:
            cap: -1
            conv: -1

        sync_delay: 0.0
        init_delay: 1.0
        init_restart_after: 0.0
        shutdown_delay: 10.0

        quality: 80
        desired_fps: 0

        host: 127.0.0.1
        port: 8082
        timeout: 2.0

        cmd:
            - "/usr/bin/ustreamer"
            - "--device=/dev/kvmd-streamer"
            - "--device-persistent"
            - "--format=uyvy"
            - "--encoder=omx"
            - "--workers=3"
            - "--quality={quality}"
            - "--desired-fps={desired_fps}"
            - "--dv-timings"
            - "--host={host}"
            - "--port={port}"
            - "--drop-same-frames=30"

        state_poll: 1.0

logging:
    version: 1
    disable_existing_loggers: false

    formatters:
        console:
            (): logging.Formatter
            style: "{"
            format: "{name:30.30} {levelname:>7} --- {message}"

    handlers:
        console:
            level: DEBUG
            class: logging.StreamHandler
            stream: ext://sys.stdout
            formatter: console

    root:
        level: INFO
        handlers:
            - console

# vim: syntax=yaml filetype=yaml
