kvmd:
    server:
        host: localhost
        port: 8081
        heartbeat: 3.0

    hid:
        pinout:
            reset: 4

        device: /dev/ttyAMA0
        speed: 115200
        reset_delay: 0.1

    atx:
        pinout:
            power_led: 16
            hdd_led: 12
            power_switch: 26
            reset_switch: 20

        click_delay: 0.1
        long_click_delay: 5.5

        state_poll: 0.1

    msd:
        pinout:
            target: 12
            reset: 13

        device: "/dev/kvmd-msd"
        init_delay: 2.0
        reset_delay: 1.0
        write_meta: true
        chunk_size: 65536

    streamer:
        pinout:
            cap: 21
            conv: 25

        sync_delay: 1.0
        init_delay: 1.0
        init_restart_after: 1.0
        shutdown_delay: 10.0

        quality: 80

        cmd:
            - "/usr/bin/ustreamer"
            - "--device=/dev/kvmd-streamer"
            - "--tv-standard=pal"
            - "--format=yuyv"
            - "--encoder=cpu"
            - "--quality={quality}"
            - "--width=720"
            - "--height=576"
            - "--fake-width=800"
            - "--fake-height=600"
            - "--host=localhost"
            - "--port=8082"

logging:
    version: 1
    disable_existing_loggers: false

    formatters:
        console:
            (): logging.Formatter
            style: "{"
            datefmt: "%H:%M:%S"
            format: "[{asctime}] {name:20.20} {levelname:>7} --- {message}"

    handlers:
        console:
            level: DEBUG
            class: logging.StreamHandler
            stream: ext://sys.stdout
            formatter: console

    root:
        level: INFO
        handlers:
            - console
