# Don't touch this file otherwise your device may stop working.
# You can find a working configuration in /usr/share/kvmd/configs.default/kvmd.

logging: !include logging.yaml

kvmd:
    server:
        host: 127.0.0.1
        port: 8081

    auth: !include auth.yaml

    hid:
        reset_pin: 4
        device: /dev/kvmd-hid

    atx:
        power_led_pin: 24
        hdd_led_pin: 22
        power_switch_pin: 23
        reset_switch_pin: 27

    msd:
        target_pin: 12
        reset_pin: 13
        device: /dev/kvmd-msd

    streamer:
        host: 127.0.0.1
        port: 8082
        cmd:
            - "/usr/bin/ustreamer"
            - "--device=/dev/kvmd-video"
            - "--persistent"
            - "--dv-timings"
            - "--format=uyvy"
            - "--encoder=omx"
            - "--workers=3"
            - "--quality={quality}"
            - "--desired-fps={desired_fps}"
            - "--host={host}"
            - "--port={port}"
            - "--drop-same-frames=30"

ipmi:
    kvmd:
        host: 127.0.0.1
        port: 8081
