# Don't touch this file otherwise your device may stop working.
# Use override.yaml to modify required settings.
# You can find a working configuration in /usr/share/kvmd/configs.default/kvmd.

override: !include override.yaml

logging: !include logging.yaml

kvmd:
    server:
        unix: /run/kvmd/kvmd.sock
        unix_rm: true
        unix_mode: 0660

    auth: !include auth.yaml

    hid:
        reset_pin: 4
        device: /dev/kvmd-hid

    atx:
        power_led_pin: 24
        hdd_led_pin: 22
        power_switch_pin: 23
        reset_switch_pin: 27

    msd:
        target_pin: 12
        reset_pin: 13
        device: /dev/kvmd-msd

    streamer:
        cap_pin: 17
        conv_pin: 18
        init_restart_after: 1
        unix: /run/kvmd/ustreamer.sock
        cmd:
            - "/usr/bin/ustreamer"
            - "--device=/dev/kvmd-video"
            - "--tv-standard=pal"
            - "--format=yuyv"
            - "--encoder=cpu"
            - "--quality={quality}"
            - "--desired-fps={desired_fps}"
            - "--resolution=720x576"
            - "--fake-resolution=800x600"
            - "--unix={unix}"
            - "--unix-rm"
            - "--unix-mode=0660"

ipmi:
    kvmd:
        unix: /run/kvmd/kvmd.sock
