# Don't touch this file otherwise your device may stop working.
# Use override.yaml to modify required settings.
# You can find a working configuration in /usr/share/kvmd/configs.default/kvmd.

override: !include override.yaml

logging: !include logging.yaml

kvmd:
    server:
        unix: /run/kvmd/kvmd.sock
        unix_rm: true
        unix_mode: 0660

    auth: !include auth.yaml

    hid:
        type: otg
        keyboard:
            device: /dev/kvmd-hid-keyboard
        mouse:
            device: /dev/kvmd-hid-mouse

    atx:
        type: disabled

    msd:
        type: otg

    streamer:
        sync_delay: 0
        init_delay: 1
        desired_fps: 30
        max_fps: 60
        unix: /run/kvmd/ustreamer.sock
        cmd:
            - "/usr/bin/ustreamer"
            - "--device=/dev/kvmd-video"
            - "--persistent"
            - "--dv-timings"
            - "--format=uyvy"
            - "--encoder=omx"
            - "--glitched-resolutions=720x480,720x576"
            - "--workers=3"
            - "--quality={quality}"
            - "--desired-fps={desired_fps}"
            - "--drop-same-frames=30"
            - "--last-as-blank=0"
            - "--unix={unix}"
            - "--unix-rm"
            - "--unix-mode=0660"
            - "--exit-on-parent-death"
            - "--no-log-colors"

ipmi:
    kvmd:
        unix: /run/kvmd/kvmd.sock
