# Don't touch this file otherwise your device may stop working.
# You can find a working configuration in /usr/share/kvmd/configs.default/kvmd.

kvmd:
    server:
        host: 127.0.0.1
        port: 8081

    hid:
        pinout:
            reset: 4
        device: /dev/kvmd-hid

    atx:
        pinout:
            power_led: 24
            hdd_led: 22
            power_switch: 23
            reset_switch: 27

    msd:
        pinout:
            target: 12
            reset: 13
        device: /dev/kvmd-msd

    streamer:
        pinout:
            cap: 17
            conv: 18
        init_restart_after: 1.0
        host: 127.0.0.1
        port: 8082
        cmd:
            - "/usr/bin/ustreamer"
            - "--device=/dev/kvmd-video"
            - "--tv-standard=pal"
            - "--format=yuyv"
            - "--encoder=cpu"
            - "--quality={quality}"
            - "--desired-fps={desired_fps}"
            - "--width=720"
            - "--height=576"
            - "--fake-width=800"
            - "--fake-height=600"
            - "--host={host}"
            - "--port={port}"

logging: !include logging.yaml
