# Don't touch this file otherwise your device may stop working.
# You can find a working configuration in /usr/share/kvmd/configs.default/kvmd.

kvmd:
    server:
        host: 127.0.0.1
        port: 8081

    hid:
        pinout:
            reset: 4
        device: /dev/kvmd-hid

    atx:
        pinout:
            power_led: 24
            hdd_led: 22
            power_switch: 23
            reset_switch: 27

    msd:
        pinout:
            target: 12
            reset: 13
        device: /dev/kvmd-msd

    streamer:
        host: 127.0.0.1
        port: 8082
        cmd:
            - "/usr/bin/ustreamer"
            - "--device=/dev/kvmd-video"
            - "--device-persistent"
            - "--format=uyvy"
            - "--encoder=omx"
            - "--workers=3"
            - "--quality={quality}"
            - "--desired-fps={desired_fps}"
            - "--dv-timings"
            - "--host={host}"
            - "--port={port}"
            - "--drop-same-frames=30"

logging: !include logging.yaml
